### ISSUE TITLE
Allow an app through

### ISSUE THREAD

**Issue by Electrijay** [MarcGuiselin/wedge#2]
I have a need to let Quickbooks continue to open in edge. I have not gotten it to respond correctly the few times it has opened a page in chrome, although it claims to be supported. It doesn't necessarily have to be edge could it could be internet explorer. As I recall Internet Explorer is being depreciated though... Thanks a bunch!

**Comment by MarcGuiselin** [comment]
Try clearing your site data in Chrome since an erroneous cookie might be the culprit.

Older versions of Quickbooks Desktop only support IE, so you should definitely update Quickbooks since newer versions support all major browsers.

If updating Quickbooks and clearing site data in Chrome doesn't work, or if you're unable to update Quickbooks, you may just need to change your default browser back to Edge in order to force Quickbooks to use it.

If that still doesn't work, uninstall Wedge and try again. Let me know whether any of these work for you, so I know whether to investigate further.

**Comment by MarcGuiselin** [comment]
Closing for now. If you have any updates on your issue, please let me know.

**Comment by Electrijay** [comment]
Thanks Marc. I'm not sure what exactly happened but somehow it seems to have cleared itself up.
Please respond to: ***@***.***
Thank you,--Jason WeaverWeaver Electric903-791-9396P.O. Box 6427Texarkana, Tx75505 

    On Wednesday, February 8, 2023 at 09:21:33 AM CST, Marc Guiselin ***@***.***> wrote:  
 
 


Closing for now. If you have any updates on your issue, please let me know.

**Comment by MarcGuiselin** [comment]
Good to hear!
